`TypeError: require(...) is not a function` with trailing ()
When I was running the tests, I was getting a `TypeError: require(...) is not a function` error. However, when I removed the trailing `()` from the required path for each test, the tests seemed to work fine.